// flow-typed signature: 4e861cd008733f4d89bf30d1ca5265fa
// flow-typed version: <<STUB>>/add-asset-html-webpack-plugin_v3.1.3/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'add-asset-html-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'add-asset-html-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'add-asset-html-webpack-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'add-asset-html-webpack-plugin/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'add-asset-html-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'add-asset-html-webpack-plugin/lib/index'>;
}
declare module 'add-asset-html-webpack-plugin/lib/utils.js' {
  declare module.exports: $Exports<'add-asset-html-webpack-plugin/lib/utils'>;
}
